PHP練習課題2
39nina/quelcode-php pull request #2
Opened 2020-05-19 02:54 UTC by 39nina

PHP練習課題2を初回提出いたします。

2020-05-19 04:33 UTC, choimake reviewed
動作要件は満たしています。OKです。

いくつかパフォーマンスの観点で修正して欲しい点がありますので、確認お願いします。

2020-05-19 04:33 UTC, choimake commented on html/php-pre-challenge2/index.php
> +for ($i = 1; $i < count($array); $i++) {
count関数ですが、これはfor文の外で実行するように修正した方がプログラムのパフォーマンスが良いです。
for文の外でcount関数を実行するように修正してください。

ex)
```
$length = count($array);
for($i = 0; $i < $length; ++$i)
```

2020-05-19 04:33 UTC, choimake commented on html/php-pre-challenge2/index.php
> +    }
現在のバブルソートの実装の仕方だと、for文が実行される回数が中のfor文が実行される回数が140回程度になるかと思います。
ただもっと回数が減らせる実装があるので、全体的に処理を見直し、なるべくfor文が回る回数を減らすような実装に修正してください。

2020-05-19 07:15 UTC, 39nina commented on html/php-pre-challenge2/index.php
> +for ($i = 1; $i < count($array); $i++) {
ご指摘いただいたcount関数含め、for文の外に出せる部分を外に移動させました。

2020-05-19 07:17 UTC, 39nina commented on html/php-pre-challenge2/index.php
> +    }
最初のfor文をデクリメントに変更し、次のfor文で確定済の値（各周で比較した一番右端の値が最大値で確定のため）を除外することで、比較範囲を毎周減らすよう変更しました。

2020-05-19 07:55 UTC, choimake reviewed
コメントしましたので確認お願いします。

2020-05-19 07:55 UTC, choimake commented on html/php-pre-challenge2/index.php
> +    }
- 「その際、$lastは1周毎に1つずつ左にずれ、比較範囲を減らしている」とありますが、コードを見る限りコメントの処理は実装できていません。もう一度確認してください。

https://github.com/39nina/quelcode-php/pull/2#discussion_r427024057


- `$index = 0`のように記号と記号の間にスペースが入っている書き方と、`$index+1`のようにスペースが入っていない書き方が混在しています。
どちらかのスタイルに統一するように修正してください。
前回の指摘漏れで申し訳ありません。

2020-05-20 02:13 UTC, 39nina commented on html/php-pre-challenge2/index.php
> +    }
・「１周毎に比較範囲を減らす」について、外側のfor文で$lastの値が更新されるように記述できていなかったため、$last = $i を追記しました。
・記号間のスペースを入れる方に統一しました。

2020-05-20 04:43 UTC, yusaku-inamura requested changes
コメントしました。
大枠はいい感じですので、細部まで仕上げてみましょう 👍 
不明点があれば質問受け付けます 🙆‍♂️

2020-05-20 04:43 UTC, yusaku-inamura commented on html/php-pre-challenge2/index.php
> +$last = $listCount - 1;
行末に余計なスペースが入っているのは好ましくないですね。
エディターの設定で保存時に消すようにしておくと自分でいちいち消す必要がないので楽です。

2020-05-20 04:43 UTC, yusaku-inamura commented on html/php-pre-challenge2/index.php
> +    // その際、$lastは1周毎に1つずつ左にずれ、比較範囲を減らしている。
直接動作に関係あるわけではないですが、`左にずれ` という書き方に少々違和感を感じますね。
コメントは人に何かを伝える手段ですので、人によって解釈が変わる可能性がある表現を使用するのは避けるべきです。

2020-05-20 04:43 UTC, yusaku-inamura commented on html/php-pre-challenge2/index.php
> +        // 右隣の数字と比較してそれより大きい場合のみ、配列の中身を入れ替えて上書き
ここも同様。
右隣とは?となる人もいますので、自分のイメージの中での話ではなく明確な言葉を使って伝えられると良いと思います。

2020-05-20 04:43 UTC, yusaku-inamura commented on html/php-pre-challenge2/index.php
> +    $last = $i;
これこの使い方なら `$last` を `$i` で代用すれば変数定義自体不要ではないですか?
もっと言うなら `$listCount` の変数定義も不要だと思います。

2020-05-20 05:03 UTC, 39nina commented on html/php-pre-challenge2/index.php
> +$last = $listCount - 1;
ご教示ありがとうございます。
VScodeの設定変更、スペース削除いたしました。

2020-05-20 05:10 UTC, 39nina commented on html/php-pre-challenge2/index.php
> +    // その際、$lastは1周毎に1つずつ左にずれ、比較範囲を減らしている。
ありがとうございます。表現を修正しました。

2020-05-20 05:10 UTC, 39nina commented on html/php-pre-challenge2/index.php
> +        // 右隣の数字と比較してそれより大きい場合のみ、配列の中身を入れ替えて上書き
こちらも修正しました。

2020-05-20 05:43 UTC, 39nina commented on html/php-pre-challenge2/index.php
> +    $last = $i;
変数をまとめ、 $i = count($array) - 1　とし、$listCount, $lastを削除しました。

2020-05-20 07:20 UTC, piasoratech approved these changes
良いかと！

2020-05-28 05:10 UTC, merged