PHP練習課題3
39nina/quelcode-php pull request #3
Opened 2020-05-26 03:42 UTC by 39nina

2020-05-26 03:46 UTC, 39nina commented
・個人サイト等参考にした箇所は念のため解釈記載しましたが、細かく載せるべきでなければ削除します。
・次の課題以降は、各要素の実装ごとにpushするようにいたします。

2020-05-26 04:16 UTC, choimake reviewed
コメントしましたので確認お願いします。

2020-05-26 04:16 UTC, choimake commented on html/php-pre-challenge3/index.php
> +    return intval($value) == $value2 && $value2 > 0;
動作要件に明確に書かれておらず申し訳ありませんが、
**「1.0」のような小数の値がtargetで設定された場合エラーを返すという仕様で実装して欲しい**です。
現在の実装だと、1.0だとのようなキリのいい小数の値の場合、処理が正常に続行される動作になっているので、エラーになるように修正してください。
（カリキュラムに「1.0」のような値はエラーで実装するようにとの旨を追記いたしました）

また、値の比較をする際は「===」を使うようにしてください。
型を意識したプログラミングができるようになりましょう。

2020-05-26 04:16 UTC, choimake commented on html/php-pre-challenge3/index.php
> +    exit();
動作要件には明確に書かれていませんが、DBエラーが発生した場合のエラーコードを設定するようにしましょう。

何のエラーコードが適切かは自力で調べてみてください。

2020-05-26 04:16 UTC, choimake commented on html/php-pre-challenge3/index.php
> +  }
インデントは揃えましょう。

2020-05-26 04:16 UTC, choimake commented on html/php-pre-challenge3/index.php
> +    $db = new PDO('mysql:dbname=test;host=mysql;charset=utf8','test', 'test');
DBの接続情報がコードの一番上と、ここのコードの二重に記載されていて混乱の元なので、

- コード上部の`$dsn = 'mysql:db...`の変数を削除する
- ここの接続情報を設定する際に、$dsnの変数を利用する

どちらかの対応で修正してください。

2020-05-26 04:16 UTC, choimake commented on html/php-pre-challenge3/index.php
> +?>
phpの閉じタグは消しましょう。
phpのみの処理が書かれているコードでは不要です。（あるとむしろバグの元になる）

2020-05-26 05:07 UTC, 39nina commented on html/php-pre-challenge3/index.php
> +?>
認識不足でした。削除いたしました。

2020-05-26 05:09 UTC, 39nina commented on html/php-pre-challenge3/index.php
> +  }
修正しました。

2020-05-26 05:17 UTC, 39nina commented on html/php-pre-challenge3/index.php
> +    $db = new PDO('mysql:dbname=test;host=mysql;charset=utf8','test', 'test');
変数$dsnを利用するよう修正しました。

2020-05-26 06:33 UTC, 39nina commented on html/php-pre-challenge3/index.php
> +    exit();
trycatch構文にしているため、PDOExceptionをスローするPDO::ERRMODE_EXCEPTIONを設定しました。

2020-05-26 06:54 UTC, 39nina commented on html/php-pre-challenge3/index.php
> +    return intval($value) == $value2 && $value2 > 0;
!type_digitと0の場合（厳密比較で比較）に、エラーを返すよう修正しました。

2020-05-26 07:32 UTC, choimake reviewed
修正ありがとうございます。
良くなってきてますが、もう少しだけ修正して欲しい部分がありますので、そちら対応お願いします。

2020-05-26 07:32 UTC, choimake commented on html/php-pre-challenge3/index.php
> +    $db = new PDO($dsn,$dbuser, $dbpassword);
`$dsn,$dbuser, $dbpassword`のように記号の間にスペースが入っていたり、入ってなかったりしている部分があります。
コード全体でスタイルは統一するようにしましょう。

2020-05-26 07:32 UTC, choimake commented on html/php-pre-challenge3/index.php
> +    http_response_code(400) ;
`http_response_code(400) ;`の`)`の間に`;`スペースが入ってます。
基本的にここにはスペースを入れる必要は無いので削除してください。

他にも同様の箇所がある場合は合わせて対応お願いします。

2020-05-26 07:32 UTC, choimake commented on html/php-pre-challenge3/index.php
> +    exit();
ここはDBエラーが発生した時に、エラーを表すレスポンスコードを`http_response_code`を使って送信するよう実装して欲しいというお願いでした。

わかりにくくて申し訳ありません。すみませんが対応お願いします。

2020-05-26 07:39 UTC, 39nina commented on html/php-pre-challenge3/index.php
> +    $db = new PDO($dsn,$dbuser, $dbpassword);
細かく見ていただいてありがとうございます。
当該箇所含め、スペースを入れる方に統一いたしました。

2020-05-26 07:42 UTC, 39nina commented on html/php-pre-challenge3/index.php
> +    http_response_code(400) ;
他には確認できなかったので、本箇所のみ不要なスペース削除しました。

2020-05-26 09:12 UTC, 39nina commented on html/php-pre-challenge3/index.php
> +    exit();
ご指示内容がわかっておらず失礼いたしました。
http_response_code(404); を挿入しました。
404は「サーバーには接続できるが、要求されたリソースが見つからない場合」とのことなので、こちらのエラーコードにしています。

2020-05-27 04:18 UTC, yusaku-inamura requested changes
レビューしました。
細々指摘あったので一旦お返ししますね。
変数名の付け方含むコードの書き方をもう少し意識できるとよりよくなると思います。
そうすることでコードの可読性、ひいては改修、デバッグのしやすさ、またレビュワーのレビュークオリティの向上につながります。
赤の他人がみてわかりやすいコードかな?と考えながら書いてみましょう。

と言ってもロジックがややこしくなれば当然可読性は下がってしまいますがそれはもう仕方がないですね 😫 
その中でいかに見やすく書くかといういわゆる努力目標というやつです。

2020-05-27 04:18 UTC, yusaku-inamura commented on html/php-pre-challenge3/index.php
> +print($json_combi);
phpに限らず、ファイルの末尾には改行を必ず含めるようにしましょう。
理由としては、POSIXと呼ばれるUNIX系OSの共通する機能における標準を定めた共通規格にて、 `ファイルは行の集合であり、行は改行にて終了する` と定められているからです。

この件に限らず、プログラムの書き方は、プロジェクトにて決められている規約が最優先となり、その次はメジャーなコーディング規約を採用するのが基本となっています。(ファイルの末尾の改行に関してはほぼ間違いなくいれることになっているはず)
それらを自動的に適用してくれるプラグインなどがあると思うので、エディタに入れておくのが一番楽ですね。

2020-05-27 04:18 UTC, yusaku-inamura commented on html/php-pre-challenge3/index.php
> +$record = array_map('intval', $record);
あまり同じ変数に対して再代入を行うのは好ましく無いですね。
当然使用するのが良いパターンもありますが、今回の場合は `array_map('intval', $records->fetchAll(PDO::FETCH_COLUMN));` とかで書けるかなと。
まあ多少好みの範疇もあります。

2020-05-27 04:18 UTC, yusaku-inamura commented on html/php-pre-challenge3/index.php
> +for($k = 1; $k < ($sumCount + 1); $k++) {
ネスト内で最初に出てくるfor文のカウンタ変数が `$k` なのはあまりメジャーではないですかね。
特別な理由がない限りは、可読性の観点から `$i` を使用するのをお勧めします。

2020-05-27 04:18 UTC, yusaku-inamura commented on html/php-pre-challenge3/index.php
> +$record = $records->fetchAll(PDO::FETCH_COLUMN);
この変数名、実際には返却値が複数あることを想定しているのに単数形になっているのはあまり良くないですね。
こういう場合は各関数が返却する値の型や意味に注目することで変数名が付けやすくなるかもしれません 🤔 

例えば、今回の場合 `$records = $db->query('SELECT * FROM prechallenge3');` の時点でrecordsという変数名を使用してしまっておりますが、ここで返却されているのは、phpマニュアルを見ると実際には PDOStatement オブジェクトです。
そのため、`$statement = $db->query('SELECT * FROM prechallenge3');` としてあげればその次の行で `$records = $statement->fetchAll(PDO::FETCH_COLUMN);` とすることにより、取得したレコードの一覧に対して `$records` という変数名を割り当てることができるのではないでしょうか。

最初のうちは関数の定義をphpマニュアルで見るのに抵抗があるかもしれませんが、読めるようになると学習効率が格段に変わるので是非意識してみてください。

2020-05-27 04:18 UTC, yusaku-inamura commented on html/php-pre-challenge3/index.php
> +    $sum = count($array);
ここも実際には `sum=和` ではなく、ただの配列のカウントですね。
その場合変数名も例えばcountとかにするのが可読性上適切ですし、次の行でしか使わないのであればなんなら `if(count($array)< $pick)`としてしまってもよいですね 👍

2020-05-27 04:18 UTC, yusaku-inamura commented on html/php-pre-challenge3/index.php
> +        $arrays[$i] = array($array[$i]);
ここのインデントが一つ少ないですね。
また、配列宣言は arrayでもできますが、 php5.4からは短縮構文で `[]` でも宣言できますので、基本的にはそちらを使いましょう。
可読性が著しく損なわれるなど特別な理由がない限りは基本的に短く書けるのが正義です 🦸‍♂️

2020-05-27 04:18 UTC, yusaku-inamura commented on html/php-pre-challenge3/index.php
> +$sumCount = count($record);
ここの `sumCount` という変数も少々違和感ですかね・・・。
単純に `count` でいい気がします。
何か理由があればそれ次第ではこの変数名でも良いです。

2020-05-27 04:18 UTC, yusaku-inamura commented on html/php-pre-challenge3/index.php
> +$json_combi = json_encode($combi);
変数名命名規則がスネークケースとキャメルケースでごっちゃになっていますね。
phpでメジャーとなるのはキャメルケースですが、最低限命名規則はどれかに統一するようにしましょう 🙆‍♂️

2020-05-27 04:18 UTC, yusaku-inamura commented on html/php-pre-challenge3/index.php
> +        return;
ここの分岐通してみましたか?
ここを通った場合、呼び出し元の変数に代入される値が `null` になり、その後のforeach以降でエラー及び警告が発生しそうです。

2020-05-27 04:18 UTC, yusaku-inamura commented on html/php-pre-challenge3/index.php
> +    http_response_code(404);
DB接続エラーの場合に404というのは少々不適切な気がしますね。
404が何を表すhttpステータスコードがもう少し調べて、適切なステータスコードは何かを考えてみましょう 🤔

2020-05-27 04:31 UTC, yusaku-inamura commented on html/php-pre-challenge3/index.php
> +    http_response_code(404);
と思ったら動作要件についさっき追加されたのでこちらご確認ください。
https://quelcode.slite.com/app/channels/LnKDoZ3TlY/notes/E9UH9zn0UT#
ただステータスコードについては軽く目を通しておいてくださいね 👀

2020-05-27 05:02 UTC, 39nina commented on html/php-pre-challenge3/index.php
> +print($json_combi);
認識不足でした。ご教示いただきありがとうございます。末尾改行挿入しました。
VScodeの設定も自動で改行入るよう変更いたしました。

2020-05-27 05:32 UTC, 39nina commented on html/php-pre-challenge3/index.php
> +$record = array_map('intval', $record);
ご教示ありがとうございます。
１行にまとめたほうがタイトになりますので、まとめる形に修正しました。

2020-05-27 05:38 UTC, 39nina commented on html/php-pre-challenge3/index.php
> +for($k = 1; $k < ($sumCount + 1); $k++) {
先のファンクション内で$i,$jと使用していたので続きと思い$kとしましたが、新たな構文なので$iを使用して問題ないと理解し、$k→$iに変更しました。

2020-05-27 06:51 UTC, 39nina commented on html/php-pre-challenge3/index.php
> +$record = $records->fetchAll(PDO::FETCH_COLUMN);
命名の考え方につきご丁寧にありがとうございます。ご指摘のとおり、複数の値が代入される変数なので、複数形にするため、ご提示いただいた案に変更しました。
（$records→$statement, $record→$records）
PHPマニュアルのPDO::queryページも確認しました。知識不足でまだ咀嚼しきれませんが、マニュアルを読むよう心がけます。

2020-05-27 06:55 UTC, 39nina commented on html/php-pre-challenge3/index.php
> +    $sum = count($array);
ご指摘のとおりです。。$countの方が適切ですので変更しました。
また、同function内で同変数が複数回出てくるため、場所はif文の外のままにいたします。

2020-05-27 07:00 UTC, 39nina commented on html/php-pre-challenge3/index.php
> +$sumCount = count($record);
sumという英単語に関する感覚がおかしいだけで理由がないので（お恥ずかしいです）、ここも$countにします。先の$iと同様に、構文が異なるため、function内で一度使用している変数名と同じでも差し支えないでしょうか？

2020-05-27 07:01 UTC, 39nina commented on html/php-pre-challenge3/index.php
> +$json_combi = json_encode($combi);
json_encodeにつられてスネークケースにしてしまっていました。
キャメルケースで統一しました。

2020-05-27 07:05 UTC, 39nina commented on html/php-pre-challenge3/index.php
> +        $arrays[$i] = array($array[$i]);
インデント修正しました。
arrayも修正しました。（他では使っていないこと確認しました）

2020-05-27 07:35 UTC, 39nina commented on html/php-pre-challenge3/index.php
> +    http_response_code(404);
クライアントエラーの400番台の状況に相当すると捉えて悩んでおりました。
500に修正しました。ステータスコードについても、一通り内容確認いたしました。

2020-05-27 08:17 UTC, 39nina commented on html/php-pre-challenge3/index.php
> +        return;
($sum < $pick) になる場合、ご指摘どおりエラーになります。確認不足で申し訳ありません。
今回のケースでは、functionを使う56行目以下で、$iが$countを上回らないfor文内での使用としているため、function内から ($sum < $pick) の分岐自体を削除します。

2020-05-28 04:32 UTC, piasoratech approved these changes
OKです！

2020-05-29 02:45 UTC, merged