PHP掲示板課題
39nina/quelcode-php pull request #4
Opened 2020-06-10 03:02 UTC by 39nina

・動作要件（RT,いいね機能）実装済です。
・SQLの動作確認済です。

2020-06-10 06:21 UTC, piasoratech requested changes
以下の内容の確認をして修正をお願いします。
- RTした投稿をRT元の投稿ユーザーが削除できてしまう

2020-06-10 06:21 UTC, piasoratech commented on html/php-challenge/rt.php
> +			$check = $st->fetch()['id'];
ここのインデントが深くなってるのは何か理由があるでしょうか？

2020-06-10 06:36 UTC, 39nina commented on html/php-challenge/rt.php
> +			$check = $st->fetch()['id'];
ありません。修正漏れのため、他に揃えました。

2020-06-10 07:08 UTC, 39nina commented
チェックいただきありがとうございました。
別途ご質問のとおり、削除に関する挙動はそのままにさせていただいています。
よろしくお願いいたします。

2020-06-10 09:09 UTC, himaru-jp requested changes
ご確認をお願いします。

2020-06-10 09:09 UTC, himaru-jp commented on html/php-challenge/fav.php
> +$post = $st->fetch();
主キーであるidで検索し、$post['id']で主キーを取得しているので、不要な処理と思われます

2020-06-10 09:09 UTC, himaru-jp commented on html/php-challenge/index.php
> +$check = $st->fetch();
ここの処理は使われていなさそうです。

2020-06-10 09:54 UTC, 39nina commented on html/php-challenge/fav.php
> +$post = $st->fetch();
ご指摘のとおり、$postは主キーid取得のみに使用していたので、当該箇所を$_REQUEST['id']に変更し、5-8行目は削除しました。

2020-06-10 10:03 UTC, 39nina commented on html/php-challenge/index.php
> +$check = $st->fetch();
作りの変更の際に削除し漏れておりました。
両変数とも同ファイル内で使用していないこと確認のうえ削除し、動作確認いたしました。

2020-06-11 02:43 UTC, himaru-jp approved these changes
レビューOKです。

2020-10-01 07:36 UTC, merged